version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker_data/database/mysql_data:/var/lib/mysql
    restart: no

  postgres:
    image: postgres:16
    container_name: postgres_16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker_data/database/postgres_data:/var/lib/postgresql/data
    restart: no
