version: "3.8"

services:
  jobmanager:
    image: flink:1.20.3
    command: jobmanager
    ports:
      - "8082:8081" # HOST_PORT (My Machine) : CONTAINER_PORT
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        # Process size needs to at least 1GB otherwise flink does not run
        jobmanager.memory.process.size: 1024m
        taskmanager.numberOfTaskSlots: 2

  taskmanager-1:
    image: flink:1.20.3
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 1024m
        taskmanager.numberOfTaskSlots: 2

  taskmanager-2:
    image: flink:1.20.3
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 1024m
        taskmanager.numberOfTaskSlots: 2
